version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: bitcoin-db-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: btc_db
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: test
      #MYSQL_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d